INSERT INTO CLIENTS (ID, NAME) VALUES (default, 'Aksenov Nikita');

INSERT INTO CONTACT_TYPES (ID, CONTACT_TYPE) VALUES (0, 'EMAIL');
INSERT INTO CONTACT_TYPES (ID, CONTACT_TYPE) VALUES (1, 'TELEPHONE');

INSERT INTO CONTACTS (ID, CLIENT_ID, CONTACT_TYPE_ID, CONTACT) VALUES (default, 1, 0, 'post@yandex.ru');
INSERT INTO CONTACTS (ID, CLIENT_ID, CONTACT_TYPE_ID, CONTACT) VALUES (default, 1, 0, 'mail@yandex.ru');
INSERT INTO CONTACTS (ID, CLIENT_ID, CONTACT_TYPE_ID, CONTACT) VALUES (default, 1, 0, 'email@yandex.ru');
INSERT INTO CONTACTS (ID, CLIENT_ID, CONTACT_TYPE_ID, CONTACT) VALUES (default, 1, 1, '+79234567891');
INSERT INTO CONTACTS (ID, CLIENT_ID, CONTACT_TYPE_ID, CONTACT) VALUES (default, 1, 1, '+79876543212');

